export const gloryStateData = [
  {
    2022: {
      State_Medals: [
        {
            "no_of_users": 40,
            "Medals": 50,
            "Gold": 15,
            "Silver": 22,
            "Bronze": 13,
            "Cashes": 694,
            "winnings": 21831698.28,
            "state": "Maharashtra"
        },
        {
            "no_of_users": 33,
            "Medals": 43,
            "Gold": 14,
            "Silver": 10,
            "Bronze": 19,
            "Cashes": 573,
            "winnings": 17736953.51,
            "state": "New Delhi"
        },
        {
            "no_of_users": 19,
            "Medals": 35,
            "Gold": 15,
            "Silver": 10,
            "Bronze": 10,
            "Cashes": 370,
            "winnings": 12533168.2,
            "state": "Rajasthan"
        },
        {
            "no_of_users": 25,
            "Medals": 29,
            "Gold": 6,
            "Silver": 8,
            "Bronze": 15,
            "Cashes": 390,
            "winnings": 12103428.7,
            "state": "Uttar Pradesh"
        },
        {
            "no_of_users": 16,
            "Medals": 21,
            "Gold": 6,
            "Silver": 8,
            "Bronze": 7,
            "Cashes": 313,
            "winnings": 11804581.26,
            "state": "Haryana"
        },
        {
            "no_of_users": 10,
            "Medals": 12,
            "Gold": 4,
            "Silver": 3,
            "Bronze": 5,
            "Cashes": 179,
            "winnings": 9891496.07,
            "state": "Goa"
        },
        {
            "no_of_users": 11,
            "Medals": 12,
            "Gold": 6,
            "Silver": 4,
            "Bronze": 2,
            "Cashes": 118,
            "winnings": 6113504.93,
            "state": "Karnataka"
        },
        {
            "no_of_users": 9,
            "Medals": 11,
            "Gold": 5,
            "Silver": 4,
            "Bronze": 2,
            "Cashes": 107,
            "winnings": 4560340.5,
            "state": "West Bengal"
        },
        {
            "no_of_users": 5,
            "Medals": 8,
            "Gold": 2,
            "Silver": 5,
            "Bronze": 1,
            "Cashes": 79,
            "winnings": 4280805.12,
            "state": "Punjab"
        },
        {
            "no_of_users": 6,
            "Medals": 7,
            "Gold": 2,
            "Silver": 1,
            "Bronze": 4,
            "Cashes": 75,
            "winnings": 1194041.48,
            "state": "Bihar"
        },
        {
            "no_of_users": 3,
            "Medals": 5,
            "Gold": 1,
            "Silver": 3,
            "Bronze": 1,
            "Cashes": 53,
            "winnings": 1592535.64,
            "state": "Madhya Pradesh"
        },
        {
            "no_of_users": 1,
            "Medals": 3,
            "Gold": 1,
            "Silver": 2,
            "Bronze": "",
            "Cashes": 22,
            "winnings": 750657.9,
            "state": "Himachal Pradesh"
        },
        {
            "no_of_users": 3,
            "Medals": 3,
            "Gold": 1,
            "Silver": 2,
            "Bronze": "",
            "Cashes": 11,
            "winnings": 4556434.24,
            "state": "Jharkhand"
        },
        {
            "no_of_users": 3,
            "Medals": 3,
            "Gold": 3,
            "Silver": "",
            "Bronze": "",
            "Cashes": 32,
            "winnings": 2300266.54,
            "state": "Tamil Nadu"
        },
        {
            "no_of_users": 2,
            "Medals": 3,
            "Gold": 1,
            "Silver": 2,
            "Bronze": "",
            "Cashes": 65,
            "winnings": 2564419.18,
            "state": "Uttarakhand"
        },
        {
            "no_of_users": 2,
            "Medals": 2,
            "Gold": 1,
            "Silver": "",
            "Bronze": 1,
            "Cashes": 23,
            "winnings": 601093.48,
            "state": "Chhattisgarh"
        },
        {
            "no_of_users": 2,
            "Medals": 2,
            "Gold": "",
            "Silver": "",
            "Bronze": 2,
            "Cashes": 43,
            "winnings": 449372.69,
            "state": "Delhi"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": "",
            "Bronze": "",
            "Cashes": 4,
            "winnings": 186518.48,
            "state": "Arunachal Pradesh"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": "",
            "Silver": "",
            "Bronze": 1,
            "Cashes": 12,
            "winnings": 134045.84,
            "state": "Jammu and Kashmir"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 16,
            "winnings": 336003.15,
            "state": "Jammu and Kashmir"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 0,
            "Bronze": 1,
            "Cashes": 7,
            "winnings": 124273.06,
            "state": "JammuandKashmir"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 1,
            "Bronze": 0,
            "Cashes": 10,
            "winnings": 113792.72,
            "state": "Nagaland"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 1,
            "Bronze": 0,
            "Cashes": 2,
            "winnings": 108632.8,
            "state": "Select State"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 12,
            "winnings": 655727.25,
            "state": "Tamil Nadu"
        },
        {
            "no_of_users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 11,
            "winnings": 74563.74,
            "state": "WestBengal"
        }
    ],
      State_Winnings: [
        {
          no_of_users: 40,
          Medals: 50,
          Gold: 15,
          Silver: 22,
          Bronze: 13,
          Cashes: 694,
          winnings: 21831698.28,
          state: "Maharashtra",
        },
        {
          no_of_users: 33,
          Medals: 43,
          Gold: 14,
          Silver: 10,
          Bronze: 19,
          Cashes: 573,
          winnings: 17736953.51,
          state: "New Delhi",
        },
        {
          no_of_users: 19,
          Medals: 35,
          Gold: 15,
          Silver: 10,
          Bronze: 10,
          Cashes: 370,
          winnings: 12533168.2,
          state: "Rajasthan",
        },
        {
          no_of_users: 25,
          Medals: 29,
          Gold: 6,
          Silver: 8,
          Bronze: 15,
          Cashes: 390,
          winnings: 12103428.6999999,
          state: "Uttar Pradesh",
        },
        {
          no_of_users: 16,
          Medals: 21,
          Gold: 6,
          Silver: 8,
          Bronze: 7,
          Cashes: 313,
          winnings: 11804581.26,
          state: "Haryana",
        },
        {
          no_of_users: 10,
          Medals: 12,
          Gold: 4,
          Silver: 3,
          Bronze: 5,
          Cashes: 179,
          winnings: 9891496.06999999,
          state: "Goa",
        },
        {
          no_of_users: 11,
          Medals: 12,
          Gold: 6,
          Silver: 4,
          Bronze: 2,
          Cashes: 118,
          winnings: 6113504.93,
          state: "Karnataka",
        },
        {
          no_of_users: 9,
          Medals: 11,
          Gold: 5,
          Silver: 4,
          Bronze: 2,
          Cashes: 107,
          winnings: 4560340.49999999,
          state: "West Bengal",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 11,
          winnings: 4556434.24,
          state: "Jharkhand",
        },
        {
          no_of_users: 5,
          Medals: 8,
          Gold: 2,
          Silver: 5,
          Bronze: 1,
          Cashes: 79,
          winnings: 4280805.12,
          state: "Punjab",
        },
        {
          no_of_users: 2,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 65,
          winnings: 2564419.18,
          state: "Uttarakhand",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 3,
          Silver: 0,
          Bronze: 0,
          Cashes: 32,
          winnings: 2300266.54,
          state: "Tamil Nadu",
        },
        {
          no_of_users: 3,
          Medals: 5,
          Gold: 1,
          Silver: 3,
          Bronze: 1,
          Cashes: 53,
          winnings: 1592535.64,
          state: "Madhya Pradesh",
        },
        {
          no_of_users: 6,
          Medals: 7,
          Gold: 2,
          Silver: 1,
          Bronze: 4,
          Cashes: 75,
          winnings: 1194041.48,
          state: "Bihar",
        },
        {
          no_of_users: 1,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 22,
          winnings: 750657.9,
          state: "Himachal Pradesh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 1,
          Silver: 0,
          Bronze: 1,
          Cashes: 23,
          winnings: 601093.48,
          state: "Chhattisgarh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 0,
          Silver: 0,
          Bronze: 2,
          Cashes: 43,
          winnings: 449372.689999999,
          state: "Delhi",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 1,
          Silver: 0,
          Bronze: 0,
          Cashes: 4,
          winnings: 186518.48,
          state: "Arunachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 12,
          winnings: 134045.84,
          state: "Jammu and Kashmir",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 1,
          winnings: 57364.5,
          state: "Null",
        },
      ],
      State_Cashes: [
        {
          no_of_users: 40,
          Medals: 50,
          Gold: 15,
          Silver: 22,
          Bronze: 13,
          Cashes: 694,
          winnings: 21831698.28,
          state: "Maharashtra",
        },
        {
          no_of_users: 33,
          Medals: 43,
          Gold: 14,
          Silver: 10,
          Bronze: 19,
          Cashes: 573,
          winnings: 17736953.51,
          state: "New Delhi",
        },
        {
          no_of_users: 25,
          Medals: 29,
          Gold: 6,
          Silver: 8,
          Bronze: 15,
          Cashes: 390,
          winnings: 12103428.6999999,
          state: "Uttar Pradesh",
        },
        {
          no_of_users: 19,
          Medals: 35,
          Gold: 15,
          Silver: 10,
          Bronze: 10,
          Cashes: 370,
          winnings: 12533168.2,
          state: "Rajasthan",
        },
        {
          no_of_users: 16,
          Medals: 21,
          Gold: 6,
          Silver: 8,
          Bronze: 7,
          Cashes: 313,
          winnings: 11804581.26,
          state: "Haryana",
        },
        {
          no_of_users: 10,
          Medals: 12,
          Gold: 4,
          Silver: 3,
          Bronze: 5,
          Cashes: 179,
          winnings: 9891496.06999999,
          state: "Goa",
        },
        {
          no_of_users: 11,
          Medals: 12,
          Gold: 6,
          Silver: 4,
          Bronze: 2,
          Cashes: 118,
          winnings: 6113504.93,
          state: "Karnataka",
        },
        {
          no_of_users: 9,
          Medals: 11,
          Gold: 5,
          Silver: 4,
          Bronze: 2,
          Cashes: 107,
          winnings: 4560340.49999999,
          state: "West Bengal",
        },
        {
          no_of_users: 5,
          Medals: 8,
          Gold: 2,
          Silver: 5,
          Bronze: 1,
          Cashes: 79,
          winnings: 4280805.12,
          state: "Punjab",
        },
        {
          no_of_users: 6,
          Medals: 7,
          Gold: 2,
          Silver: 1,
          Bronze: 4,
          Cashes: 75,
          winnings: 1194041.48,
          state: "Bihar",
        },
        {
          no_of_users: 2,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 65,
          winnings: 2564419.18,
          state: "Uttarakhand",
        },
        {
          no_of_users: 3,
          Medals: 5,
          Gold: 1,
          Silver: 3,
          Bronze: 1,
          Cashes: 53,
          winnings: 1592535.64,
          state: "Madhya Pradesh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 0,
          Silver: 0,
          Bronze: 2,
          Cashes: 43,
          winnings: 449372.689999999,
          state: "Delhi",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 3,
          Silver: 0,
          Bronze: 0,
          Cashes: 32,
          winnings: 2300266.54,
          state: "Tamil Nadu",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 1,
          Silver: 0,
          Bronze: 1,
          Cashes: 23,
          winnings: 601093.48,
          state: "Chhattisgarh",
        },
        {
          no_of_users: 1,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 22,
          winnings: 750657.9,
          state: "Himachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 12,
          winnings: 134045.84,
          state: "Jammu and Kashmir",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 11,
          winnings: 4556434.24,
          state: "Jharkhand",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 1,
          Silver: 0,
          Bronze: 0,
          Cashes: 4,
          winnings: 186518.48,
          state: "Arunachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 1,
          winnings: 57364.5,
          state: "Null",
        },
      ],
    },
    2021:{
      State_Medals:[
        {
            "# users": 36,
            "Medals": 44,
            "Gold": 12,
            "Silver": 18,
            "Bronze": 14,
            "Cashes": 436,
            "winnings": 21022083.53,
            "state": "Maharashtra"
        },
        {
            "# users": 30,
            "Medals": 34,
            "Gold": 10,
            "Silver": 11,
            "Bronze": 13,
            "Cashes": 354,
            "winnings": 14188099.22,
            "state": "New Delhi"
        },
        {
            "# users": 16,
            "Medals": 18,
            "Gold": 8,
            "Silver": 3,
            "Bronze": 7,
            "Cashes": 248,
            "winnings": 6984358.04,
            "state": "Haryana"
        },
        {
            "# users": 12,
            "Medals": 12,
            "Gold": 3,
            "Silver": 5,
            "Bronze": 4,
            "Cashes": 123,
            "winnings": 5306097.54,
            "state": "Karnataka"
        },
        {
            "# users": 10,
            "Medals": 12,
            "Gold": 5,
            "Silver": 3,
            "Bronze": 4,
            "Cashes": 121,
            "winnings": 3887729.78,
            "state": "Uttar Pradesh"
        },
        {
            "# users": 7,
            "Medals": 11,
            "Gold": 6,
            "Silver": 4,
            "Bronze": 1,
            "Cashes": 94,
            "winnings": 10666032.92,
            "state": "Rajasthan"
        },
        {
            "# users": 7,
            "Medals": 10,
            "Gold": 1,
            "Silver": 6,
            "Bronze": 3,
            "Cashes": 119,
            "winnings": 7488999.7,
            "state": "Punjab"
        },
        {
            "# users": 6,
            "Medals": 7,
            "Gold": 2,
            "Silver": 1,
            "Bronze": 4,
            "Cashes": 90,
            "winnings": 3542778.68,
            "state": "Goa"
        },
        {
            "# users": 7,
            "Medals": 7,
            "Gold": 2,
            "Silver": 4,
            "Bronze": 1,
            "Cashes": 49,
            "winnings": 4227708.98,
            "state": "Madhya Pradesh"
        },
        {
            "# users": 7,
            "Medals": 7,
            "Gold": 2,
            "Silver": 2,
            "Bronze": 3,
            "Cashes": 63,
            "winnings": 2773711.59,
            "state": "West Bengal"
        },
        {
            "# users": 4,
            "Medals": 6,
            "Gold": 2,
            "Silver": 2,
            "Bronze": 2,
            "Cashes": 71,
            "winnings": 4048003.74,
            "state": "Bihar"
        },
        {
            "# users": 5,
            "Medals": 5,
            "Gold": 4,
            "Silver": 0,
            "Bronze": 1,
            "Cashes": 26,
            "winnings": 2089365.5,
            "state": "Jharkhand"
        },
        {
            "# users": 3,
            "Medals": 4,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 3,
            "Cashes": 25,
            "winnings": 480887.98,
            "state": "Manipur"
        },
        {
            "# users": 2,
            "Medals": 2,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 1,
            "Cashes": 13,
            "winnings": 369773.06,
            "state": "Kerala"
        },
        {
            "# users": 1,
            "Medals": 2,
            "Gold": 0,
            "Silver": 0,
            "Bronze": 2,
            "Cashes": 18,
            "winnings": 663782.66,
            "state": "NewDelhi"
        },
        {
            "# users": 2,
            "Medals": 2,
            "Gold": 0,
            "Silver": 2,
            "Bronze": 0,
            "Cashes": 41,
            "winnings": 464339.65,
            "state": "Uttarakhand"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 2,
            "winnings": 51657.41,
            "state": "Arunachal Pradesh"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 1,
            "Bronze": 0,
            "Cashes": 6,
            "winnings": 226654.6,
            "state": "Delhi"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 5,
            "winnings": 203051.13,
            "state": "Himachal Pradesh"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 16,
            "winnings": 336003.15,
            "state": "Jammu and Kashmir"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 0,
            "Bronze": 1,
            "Cashes": 7,
            "winnings": 124273.06,
            "state": "JammuandKashmir"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 1,
            "Bronze": 0,
            "Cashes": 10,
            "winnings": 113792.72,
            "state": "Nagaland"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 0,
            "Silver": 1,
            "Bronze": 0,
            "Cashes": 2,
            "winnings": 108632.8,
            "state": "Select State"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 12,
            "winnings": 655727.25,
            "state": "Tamil Nadu"
        },
        {
            "# users": 1,
            "Medals": 1,
            "Gold": 1,
            "Silver": 0,
            "Bronze": 0,
            "Cashes": 11,
            "winnings": 74563.74,
            "state": "WestBengal"
        }
    ],
    State_Winnings: [
      {
          "# users": 36,
          "Medals": 44,
          "Gold": 12,
          "Silver": 18,
          "Bronze": 14,
          "Cashes": 436,
          "winnings": 21022083.53,
          "state": "Maharashtra"
      },
      {
          "# users": 30,
          "Medals": 34,
          "Gold": 10,
          "Silver": 11,
          "Bronze": 13,
          "Cashes": 354,
          "winnings": 14188099.22,
          "state": "New Delhi"
      },
      {
          "# users": 7,
          "Medals": 11,
          "Gold": 6,
          "Silver": 4,
          "Bronze": 1,
          "Cashes": 94,
          "winnings": 10666032.92,
          "state": "Rajasthan"
      },
      {
          "# users": 7,
          "Medals": 10,
          "Gold": 1,
          "Silver": 6,
          "Bronze": 3,
          "Cashes": 119,
          "winnings": 7488999.7,
          "state": "Punjab"
      },
      {
          "# users": 16,
          "Medals": 18,
          "Gold": 8,
          "Silver": 3,
          "Bronze": 7,
          "Cashes": 248,
          "winnings": 6984358.04,
          "state": "Haryana"
      },
      {
          "# users": 12,
          "Medals": 12,
          "Gold": 3,
          "Silver": 5,
          "Bronze": 4,
          "Cashes": 123,
          "winnings": 5306097.54,
          "state": "Karnataka"
      },
      {
          "# users": 7,
          "Medals": 7,
          "Gold": 2,
          "Silver": 4,
          "Bronze": 1,
          "Cashes": 49,
          "winnings": 4227708.98,
          "state": "Madhya Pradesh"
      },
      {
          "# users": 4,
          "Medals": 6,
          "Gold": 2,
          "Silver": 2,
          "Bronze": 2,
          "Cashes": 71,
          "winnings": 4048003.74,
          "state": "Bihar"
      },
      {
          "# users": 10,
          "Medals": 12,
          "Gold": 5,
          "Silver": 3,
          "Bronze": 4,
          "Cashes": 121,
          "winnings": 3887729.78,
          "state": "Uttar Pradesh"
      },
      {
          "# users": 6,
          "Medals": 7,
          "Gold": 2,
          "Silver": 1,
          "Bronze": 4,
          "Cashes": 90,
          "winnings": 3542778.68,
          "state": "Goa"
      },
      {
          "# users": 7,
          "Medals": 7,
          "Gold": 2,
          "Silver": 2,
          "Bronze": 3,
          "Cashes": 63,
          "winnings": 2773711.59,
          "state": "West Bengal"
      },
      {
          "# users": 5,
          "Medals": 5,
          "Gold": 4,
          "Silver": 0,
          "Bronze": 1,
          "Cashes": 26,
          "winnings": 2089365.5,
          "state": "Jharkhand"
      },
      {
          "# users": 1,
          "Medals": 2,
          "Gold": 0,
          "Silver": 0,
          "Bronze": 2,
          "Cashes": 18,
          "winnings": 663782.66,
          "state": "NewDelhi"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 0,
          "Cashes": 12,
          "winnings": 655727.25,
          "state": "Tamil Nadu"
      },
      {
          "# users": 3,
          "Medals": 4,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 3,
          "Cashes": 25,
          "winnings": 480887.98,
          "state": "Manipur"
      },
      {
          "# users": 2,
          "Medals": 2,
          "Gold": 0,
          "Silver": 2,
          "Bronze": 0,
          "Cashes": 41,
          "winnings": 464339.65,
          "state": "Uttarakhand"
      },
      {
          "# users": 2,
          "Medals": 2,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 1,
          "Cashes": 13,
          "winnings": 369773.06,
          "state": "Kerala"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 0,
          "Cashes": 16,
          "winnings": 336003.15,
          "state": "Jammu and Kashmir"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 0,
          "Silver": 1,
          "Bronze": 0,
          "Cashes": 6,
          "winnings": 226654.6,
          "state": "Delhi"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 0,
          "Cashes": 5,
          "winnings": 203051.13,
          "state": "Himachal Pradesh"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 0,
          "Silver": 0,
          "Bronze": 1,
          "Cashes": 7,
          "winnings": 124273.06,
          "state": "JammuandKashmir"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 0,
          "Silver": 1,
          "Bronze": 0,
          "Cashes": 10,
          "winnings": 113792.72,
          "state": "Nagaland"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 0,
          "Silver": 1,
          "Bronze": 0,
          "Cashes": 2,
          "winnings": 108632.8,
          "state": "Select State"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 0,
          "Cashes": 11,
          "winnings": 74563.74,
          "state": "WestBengal"
      },
      {
          "# users": 1,
          "Medals": 1,
          "Gold": 1,
          "Silver": 0,
          "Bronze": 0,
          "Cashes": 2,
          "winnings": 51657.41,
          "state": "Arunachal Pradesh"
      }
  ],
  State_Cashes: [
    {
        "# users": 36,
        "Medals": 44,
        "Gold": 12,
        "Silver": 18,
        "Bronze": 14,
        "Cashes": 436,
        "winnings": 21022083.53,
        "state": "Maharashtra"
    },
    {
        "# users": 30,
        "Medals": 34,
        "Gold": 10,
        "Silver": 11,
        "Bronze": 13,
        "Cashes": 354,
        "winnings": 14188099.22,
        "state": "New Delhi"
    },
    {
        "# users": 16,
        "Medals": 18,
        "Gold": 8,
        "Silver": 3,
        "Bronze": 7,
        "Cashes": 248,
        "winnings": 6984358.04,
        "state": "Haryana"
    },
    {
        "# users": 12,
        "Medals": 12,
        "Gold": 3,
        "Silver": 5,
        "Bronze": 4,
        "Cashes": 123,
        "winnings": 5306097.54,
        "state": "Karnataka"
    },
    {
        "# users": 10,
        "Medals": 12,
        "Gold": 5,
        "Silver": 3,
        "Bronze": 4,
        "Cashes": 121,
        "winnings": 3887729.78,
        "state": "Uttar Pradesh"
    },
    {
        "# users": 7,
        "Medals": 10,
        "Gold": 1,
        "Silver": 6,
        "Bronze": 3,
        "Cashes": 119,
        "winnings": 7488999.7,
        "state": "Punjab"
    },
    {
        "# users": 7,
        "Medals": 11,
        "Gold": 6,
        "Silver": 4,
        "Bronze": 1,
        "Cashes": 94,
        "winnings": 10666032.92,
        "state": "Rajasthan"
    },
    {
        "# users": 6,
        "Medals": 7,
        "Gold": 2,
        "Silver": 1,
        "Bronze": 4,
        "Cashes": 90,
        "winnings": 3542778.68,
        "state": "Goa"
    },
    {
        "# users": 4,
        "Medals": 6,
        "Gold": 2,
        "Silver": 2,
        "Bronze": 2,
        "Cashes": 71,
        "winnings": 4048003.74,
        "state": "Bihar"
    },
    {
        "# users": 7,
        "Medals": 7,
        "Gold": 2,
        "Silver": 2,
        "Bronze": 3,
        "Cashes": 63,
        "winnings": 2773711.59,
        "state": "West Bengal"
    },
    {
        "# users": 7,
        "Medals": 7,
        "Gold": 2,
        "Silver": 4,
        "Bronze": 1,
        "Cashes": 49,
        "winnings": 4227708.98,
        "state": "Madhya Pradesh"
    },
    {
        "# users": 2,
        "Medals": 2,
        "Gold": 0,
        "Silver": 2,
        "Bronze": 0,
        "Cashes": 41,
        "winnings": 464339.65,
        "state": "Uttarakhand"
    },
    {
        "# users": 5,
        "Medals": 5,
        "Gold": 4,
        "Silver": 0,
        "Bronze": 1,
        "Cashes": 26,
        "winnings": 2089365.5,
        "state": "Jharkhand"
    },
    {
        "# users": 3,
        "Medals": 4,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 3,
        "Cashes": 25,
        "winnings": 480887.98,
        "state": "Manipur"
    },
    {
        "# users": 1,
        "Medals": 2,
        "Gold": 0,
        "Silver": 0,
        "Bronze": 2,
        "Cashes": 18,
        "winnings": 663782.66,
        "state": "NewDelhi"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 0,
        "Cashes": 16,
        "winnings": 336003.15,
        "state": "Jammu and Kashmir"
    },
    {
        "# users": 2,
        "Medals": 2,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 1,
        "Cashes": 13,
        "winnings": 369773.06,
        "state": "Kerala"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 0,
        "Cashes": 12,
        "winnings": 655727.25,
        "state": "Tamil Nadu"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 0,
        "Cashes": 11,
        "winnings": 74563.74,
        "state": "WestBengal"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 0,
        "Silver": 1,
        "Bronze": 0,
        "Cashes": 10,
        "winnings": 113792.72,
        "state": "Nagaland"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 0,
        "Silver": 0,
        "Bronze": 1,
        "Cashes": 7,
        "winnings": 124273.06,
        "state": "JammuandKashmir"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 0,
        "Silver": 1,
        "Bronze": 0,
        "Cashes": 6,
        "winnings": 226654.6,
        "state": "Delhi"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 0,
        "Cashes": 5,
        "winnings": 203051.13,
        "state": "Himachal Pradesh"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 1,
        "Silver": 0,
        "Bronze": 0,
        "Cashes": 2,
        "winnings": 51657.41,
        "state": "Arunachal Pradesh"
    },
    {
        "# users": 1,
        "Medals": 1,
        "Gold": 0,
        "Silver": 1,
        "Bronze": 0,
        "Cashes": 2,
        "winnings": 108632.8,
        "state": "Select State"
    }
]
      
    }
  },
];
